# For more information, see:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool:
    name: Home Pool
    demands:
    - cmake

  steps:
  - task: CMake@1
    displayName: 'CMake ..'
    inputs:
      cmakeArgs: '..'

  - task: CMake@1
    displayName: 'CMake --build . --config Debug'
    inputs:
      cmakeArgs: '--build . --config Debug'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
